### ISSUE TITLE
Not Found - GET https://registry.npmjs.org/@proyecto26%2frecord-audio-button - Not found

### ISSUE THREAD

**Issue by fukemy** [proyecto26/record-audio-button-enterprise#2]
hi i want to appy ur lib inside my react native project but got this error, can u help? Thanks

**Comment by jdnichollsc** [comment]
Hello dude, you can't use Web components from React Native projects.

Best Regards,
Juan

**Comment by fukemy** [comment]
hi, im learning mobile react native app. I just copy text into terminal of visual code then run it. I think ur lib can used for mobile ?

**Comment by jdnichollsc** [comment]
This lib can't be used from React Native because I'm using web dependencies :)

**Comment by fukemy** [comment]
ok tks :(
